### ISSUE TITLE
Add a stop button

### ISSUE THREAD

**Issue by geplus** [linuxmint/xplayer#15]
Hi,
quoting  #13
Personally, I really use the stop button using video and audio palyers, the function is little different: the stop button stop both a playlist or a single file, so you have to restart from 0 what was you playing.
I think it's simple to implement a traditional stop button (that you could show/hide optionally) as a player's function or simply with a dedicated plugin, for all the users like me that likes the stop button in the players, as other player do already , like vlc and gnome-mplayer.

**Comment by anandrkris** [comment]
Even I use Stop button (in SMPlayer) to reset to T0. For instance, when I downland a movie file, I randomly view the scenes to assess quality of print and use 'Stop' to start watching from beginning. I can think of various other use cases as well but quite simply it is the flexibility to start viewing something from beginning for various reasons.

**Comment by clefebvre** [comment]
Hi,

I don't think we need a stop button and so we probably won't add one.

That said, you should be able to reset the position quickly with the back button, and as it is now, that doesn't work well because that button is insensitive when playing the first or only element in the playlist.

We'll fix this issue.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/xplayer/commit/6016f80d26e87d3fce0b7ec970913d7782ea3a6b
